### ISSUE TITLE
PeerConnections fail after [rtc::impl::IceTransport::LogCallback@363] juice: conn_poll.c:311: poll failed, errno=10038

### ISSUE THREAD

**Issue by Sniperlyf3** [paullouisageneau/libdatachannel#1252]
## Notes:
- I was only able to replicate this issue on Windows. I wasn’t able to reproduce this behavior on WSL (Ubuntu 22.04.4 LTS on Windows 10 x86_64).
- The issue seems to be timing-related. I wasn’t able to replicate this issue with verbose logging and had to close about 100 connections at a time for this to occur.
## Replication steps:
- Create 100 PeerConnection objects (connected to some other peers).
- Remove them.
- Repeat the above steps.
## Result:
```[rtc::impl::IceTransport::LogCallback@363] juice: conn_poll.c:311: poll failed, errno=10038```
- Within a few seconds, all the other peers will start failing.
- No more PeerConnection connections will be created; it is stuck in a stable state. The application has to be restarted before any new connections can be made.
## Expected behavior:
To not prevent all future PeerConnections from being able to establish a connection.

I don’t know if this is a timing issue from libdatachannel or if this should be addressed in libjuice. Please advise.

**Comment by paullouisageneau** [comment]
This error was fixed by https://github.com/paullouisageneau/libjuice/pull/198. You must use a very old version of libdatachannel or libjuice.

**Comment by Sniperlyf3** [comment]
It appears that _WIN32 is not being defined during the compilation of libjuice when using vcpkg. This issue persists even with a fresh installation of Windows and Visual Studio 2022 Community Edition with C++ development tools. Consequently, anyone using libjuice on Windows and installing it via vcpkg is likely to encounter the same issues that have already been addressed.

**Comment by Sniperlyf3** [comment]
Fixed in https://github.com/paullouisageneau/libjuice/pull/272
