### ISSUE TITLE
PeerConnection fails after several recreations

### ISSUE THREAD

**Issue by dshurbin** [paullouisageneau/libdatachannel#323]
Good day.
I'm writing a program to route RTP traffic from RTSP cameras to a web browser. I'm sending raw h264 frames via datachannel (sorry to say, I didn't get how to operate with media track). And i faced two issues: 
1) datachannel fails after ~600+ seconds
2) some cameras have a latency, which is accumulating and i can get > 1 minute in some cases
To fight the issues, I'm sending retrains each 2 minutes to reinitiate the connection, it does fast enough ~1.5 seconds. Doing this this way:
- call PeerConnection.close()
- in PeerConnection->onStateChange() when it happens,  changing client state to RETRAIN, then forming and sending retrain request
- in the websocket control channel when receiving new SDP, checking if client in retrain mode, calling pc->reset() and creating a new PeerConnection calling client->pc = createPeerConnection(...). the "pc" is shared_ptr<PeerConnection>
everything seemes to be ok, but after ~14 retrains system fails with "LeakSanitizer: Thread limit (8192 threads) exceeded. Dying.", on "-fSanitize=address" it is "...AddressSanitizer failed to allocate 0x1000 (4096) bytes of InternalScopedBuffer..." and so on.
if I just close() and then trying to use PeerConnection without destruction, I can not set remote SDP and remote Ice candidate, If I do PeerConnection->remoteDescription()->reset(), I still can not do this. 
Can You please advice, how to reinitiate PeerConnection session properly? It is supposed that there are many clients from different hosts will use  their own instance of PeerConnection each.
I'm quite new with shared_ptr, I think the problem is there and I think I do not understand correctly the mechanism.

Respectfully, Dmitry.

**Comment by paullouisageneau** [comment]
> datachannel fails after ~600+ seconds

Do you use the latest version? A similar issue, caused by broken path MTU discovery in usrsctp, was fixed in v0.11.0.

> some cameras have a latency, which is accumulating and i can get > 1 minute in some cases

That's expected, Data Channels have congestion control and will buffer if the network can't achieve the source bitrate, adding more and more delay.

You should definitely use media tracks instead to transmit near-realtime media. You could look into the `streamer` example to see how to manipulate tracks.

> • in the websocket control channel when receiving new SDP, checking if client in retrain mode, calling pc->reset() and creating a new PeerConnection calling client->pc = createPeerConnection(...). the "pc" is shared_ptr

This is indeed the right way to reconnect, destroying then recreating the `PeerConnection`. Additionally, you might want to explicitly close it on both sides.

> everything seemes to be ok, but after ~14 retrains system fails with "LeakSanitizer: Thread limit (8192 threads) exceeded. Dying.", on "-fSanitize=address" it is "...AddressSanitizer failed to allocate 0x1000 (4096) bytes of InternalScopedBuffer..." and so on.

There might be a leak somewhere. Are you sure a copy of the `shared_ptr` to the `PeerConnection` is not stored somewhere else? (in which case, releasing only one of the pointers with `reset()` won't destroy or even close it). 

> if I just close() and then trying to use PeerConnection without destruction, I can not set remote SDP and remote Ice candidate

Indeed, you may not reuse a PeerConnection in closed state.

> If I do PeerConnection->remoteDescription()->reset(), I still can not do this.

You can't modify the descriptions, the getters only return a copy.

**Comment by dshurbin** [comment]
Good day.
Thanks a lot for the prompt answer!

> Do you use the latest version? A similar issue, caused by broken path MTU discovery in usrsctp, was fixed in v0.11.0.
 No, it was the old one. Now I switched to the current version. And, yes - this disconnection is disappeared, but time before crash remained almost the same. I tried to figure out what happened and looked with the "top" command. the memory used by process was increasing approx. 1 MB/sec. I didn't found memory leakage at my code, but may be I was looking wrong, so I'm still in searching and debugging.

> That's expected, Data Channels have congestion control and will buffer if the network can't achieve the source bitrate, adding more and more delay.
> 
> You should definitely use media tracks instead to transmit near-realtime media. You could look into the `streamer` example to see how to manipulate tracks.
I did. The streamer works perfectly! And it overcomes my maximum lifetime I reached. But it is strange - when I ran it and used the "top" I found, that at the beginning, after ~3 minutes the RES was 18524, then it was rising bit by bit. After 30 minutes it was about 20636. Anyway, I will definitely switch to using media tracks.

> This is indeed the right way to reconnect, destroying then recreating the `PeerConnection`. Additionally, you might want to explicitly close it on both sides.
It does on both ends of course.  

> There might be a leak somewhere. Are you sure a copy of the `shared_ptr` to the `PeerConnection` is not stored somewhere else? (in which case, releasing only one of the pointers with `reset()` won't destroy or even close it).
I use single PeerConnection for each WebClient. actually, WebClient has two share_ptr fields - PeerConnection and DataChannel. 

> You can't modify the descriptions, the getters only return a copy.
Yep. got it.

Respectfully, Dmitry.

**Comment by dshurbin** [comment]
> I did. The streamer works perfectly! And it overcomes my maximum lifetime I reached. But it is strange - when I ran it and used the "top" I found, that at the beginning, after ~3 minutes the RES was 18524, then it was rising bit by bit. After 30 minutes it was about 20636. Anyway, I will definitely switch to using media tracks.

After an hour RES was 23816. after stopping at browser and reconnect, RES value started 25+k and continued to increase.
Respectfully, Dmitry.

**Comment by paullouisageneau** [comment]
`top` only shows the memory pages allocated at the lower level. It's normal for that number to increase a bit over the beginning of the running time depending on the dynamic allocation algorithm and memory fragmentation.

It might be a leak, or it might be normal. The easiest way to find about it is to run a debug build in valgrind.

**Comment by murat-dogan** [comment]
There was no problem last time I made the checks with Valgrind. 

https://github.com/paullouisageneau/libdatachannel/issues/223

**Comment by dshurbin** [comment]
Good day.
And still, when I send a message via datachannel, the procedure is:
- (*byte)data containing the h264 frame (splitted in portions to fit MTU) is handed to DataChannel::send(const byte *data, size_t size)
- then there it is transformed to Message as make_shared<Message>(data, data + size, Message::Binary) and handed to DataChannel::outgoing() and then to SctpTransport->send(message_ptr) 
- then it is handed to SctpTransport::TrySendMessage() and after success it returns

after DataChannel::send() I do free(data), but does the shared_ptr <Message> created from it is freeing?
because used memory of the process is growing at the rate very close to the video stream rate

**Comment by paullouisageneau** [comment]
> (*byte)data containing the h264 frame (splitted in portions to fit MTU) is handed to DataChannel::send(const byte *data, size_t size)

Well there might be a misunderstanding here, you must not split the frame arbitrarily yourself, this is instead handled by the `H264RtpPacketizer` you plug into the `Track`.

> after DataChannel::send() I do free(data), but does the shared_ptr created from it is freeing?

Yes, the library does an internal copy which will be freed when the data is actually sent.

If you sense that there is a memory leak, you can run a debug build with `valgrind --leak-check=full ...` to pinpoint what is never freed.

**Comment by paullouisageneau** [comment]
> (*byte)data containing the h264 frame (splitted in portions to fit MTU) is handed to DataChannel::send(const byte *data, size_t size)

You don't have to bother about MTU, the Data Channel handles it for you. The maximum message size is 256 KB by default.

> after DataChannel::send() I do free(data), but does the shared_ptr created from it is freeing?

Yes, the library does an internal copy which will be freed when the data is actually sent.

If you sense that there is a memory leak, you can run a debug build with valgrind --leak-check=full ... to pinpoint what is never freed.

**Comment by dshurbin** [comment]
after switching to the new library all negative effects are gone.
remaining "leakage", when process used memory was growing fast was a consequence of using compilation switch -fsanitizer=address. After its removal, RES remained stable.
Closing.
